### ISSUE TITLE
IIS with multiple worker processes not supported

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2015]
IIS has a very nice feature that allows a user to scale out a website in IIS.
This feature is called Web Garden:
![mjzl7](https://f.cloud.github.com/assets/122651/2442392/86b87b40-ae21-11e3-8c57-9b5551382e56.png)

Unfortunately, scaling out IIS this way won't work with NServiceBus.
Things that will break are:
- Callbacks

**Comment by andreasohlund** [comment]
@johnsimons with callbacks out of the core does this change things?

Can you elaborate on the issue with the event subscriptions?

**Comment by johnsimons** [comment]
@andreasohlund,

> with callbacks out of the core does this change things?

No it does not, the issue remains, our impl of callbacks relies on uniqueness of the combination of queuename + host, in this case both are the same, we would need to also take into consideration something like process id. I guess this problem also exists for when we scale out an endpoint in the same machine :(


> Can you elaborate on the issue with the event subscriptions?

The issue is that we dedup the subscribers, so because both subscribers are the same (endpointname + host), we end-up only storing one of them (I guess the first one wins).

Hope this make sense ?

**Comment by danielmarbach** [comment]
Since we are addressing the mentioned callback limitations. Should we close this issue and copy over the necessary information into https://github.com/Particular/PlatformDevelopment/issues/574 ?

**Comment by andreasohlund** [comment]
What's the status on this one now that the callbacks have been fixed? still relevant? (cc @timbussmann @SzymonPobiega @janovesk )

**Comment by timbussmann** [comment]
I'd say it's still not possible to use multiple worker processes together with the callbacks package? But since callbacks are extracted into a dedicated package, we probably need to accept this as a limitations when using callbacks. I vote to close this (potentially reraise in the callbacks repo if there is a reliable way to fix it?).

**Comment by bording** [comment]
> I'd say it's still not possible to use multiple worker processes together with the callbacks package? 

It should be possible to use now that we have `MakeInstanceUniquelyAddressable` to remove the requirement of "queue + host" being the only option for a callbacks queue name.

To be able use this correctly, each worker process would have to pass a unique value to `MakeInstanceUniquelyAddressable` to make sure they each got their own queue.

Otherwise, you're dealing with the same problem as before: not having a guaranteed unique way to address the instances created in the worker processes.

Doing this would introduce another problem though: Lots of leftover unused queues as the worker processes die and new ones get started.

**Comment by andreasohlund** [comment]
What are the action points here? Should we close this for now?

**Comment by timbussmann** [comment]
> To be able use this correctly, each worker process would have to pass a unique value to MakeInstanceUniquelyAddressable to make sure they each got their own queue.

which will essentially lead to an endless list of unused queues? (we did that a while ago with ActiveMQ transport...)

**Comment by danielmarbach** [comment]
Extract from

[Why You Shouldn’t Use Web Gardens in IIS Week 24](http://dotnetslackers.com/articles/iis/Why-You-Shouldnt-Use-Web-Gardens-in-IIS-Week-24.aspx)

## Pros

- For contention with concurrent requests
- PHP ISAPI mode may benefit
- Troubleshooting measure

## Cons

- In-proc session state won't work
- Shared memory cache is duplicated (more memory waste)
- First hit per worker process
- Base memory adds up
- Troublehshooting involves more processes
- If the problem is CPU bound web garden doesn't help, it makes it worse
- Web garden is just a band-aid

Make asynchronous calls instead, remove contention...

Consider instead https://support.microsoft.com/en-us/kb/821268

Since NSB v6 is completely asynchronous, we reduced contention etc. I'm closing this. Not worth pursuing
