### ISSUE TITLE
InMemoryPersistence with Sagas immediately blows up and tears down the endpoint

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3244]
@anetteha detected this during the NSBCon Hackathon. When you use `InMemoryPersistence` with Sagas with V6 you get the following exception:

```
Unhandled Exception: System.Exception: InMemorySagaPersister concurrency violati
on: saga entity Id[cd1f4e97-17ac-496c-a9d5-a562014cf6e5] already saved.
   at NServiceBus.InMemorySagaPersister.VersionedSagaEntity.ConcurrencyCheck(ICo
ntainSagaData sagaEntity, Int32 currentVersion) in C:\BuildAgent\work\3206e2123f
54fce4\src\NServiceBus.Core\Persistence\InMemory\SagaPersister\InMemorySagaPersi
ster.cs:line 172
   at NServiceBus.InMemorySagaPersister.<>c__DisplayClass4_0.<Update>b__0() in C
:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Persistence\InMemory\Sag
aPersister\InMemorySagaPersister.cs:line 101
   at NServiceBus.InMemoryTransaction.Commit() in C:\BuildAgent\work\3206e2123f5
4fce4\src\NServiceBus.Core\Persistence\InMemory\InMemoryTransaction.cs:line 17
   at NServiceBus.InMemoryTransactionalSynchronizedStorageAdapter.EnlistmentNoti
fication.Prepare(PreparingEnlistment preparingEnlistment) in C:\BuildAgent\work\
3206e2123f54fce4\src\NServiceBus.Core\Persistence\InMemory\InMemoryTransactional
SynchronizedStorageAdapter.cs:line 48
   at System.Transactions.InternalEnlistment.System.Transactions.IEnlistmentNoti
ficationInternal.Prepare(IPromotedEnlistment preparingEnlistment)
   at System.Transactions.Oletx.OletxVolatileEnlistment.Prepare(OletxVolatileEnl
istmentContainer container)
   at System.Transactions.Oletx.OletxPhase1VolatileEnlistmentContainer.VoteReque
st()
   at System.Transactions.Oletx.OletxTransactionManager.ShimNotificationCallback
(Object state, Boolean timeout)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback
(Object state, Boolean timedOut)
```

The exception happens in the background and tears down the endpoint because it is an Unobserved unhandled exception.

Yes I know `InMemoryPersistence` is not production ready. But it should at least work with concurrency greater than one ;)

**Comment by danielmarbach** [comment]
@anetteha @WilliamBZA and I fixed the issue as part of 

https://github.com/Particular/NServiceBus/pull/3287

Thanks again for raising it!

**Comment by Niklas-Peter** [comment]
I still have this problem in NSB 6.1.3. If I set `config.LimitMessageProcessingConcurrencyTo(1)` it works, else not. 

In my use case endpoint A sends messages in a loop to endpoint B. Endpoint B hosts the saga and I get the same exception as described in this issue.

**Comment by danielmarbach** [comment]
@Niklas-Peter do you get the same exception and it tears down the same endpoint or do you just get the same exception in the logs?

**Comment by Niklas-Peter** [comment]
Just the same exception.

**Comment by danielmarbach** [comment]
I don't want to imply that it is great what you are seeing since the InMemorySagaPersister needs to be improved. We still have a few issues to solve there like https://github.com/Particular/NServiceBus/issues/4407 

That being said the exception you are seeing can happen but should eventually resolve itself. Will the message be moved into the error queue or does Immediate and Delayed Retry solve it over time?

**Comment by Niklas-Peter** [comment]
It is resolved by immediate retries. As I do not intend to use the InMemoryPersistence in production, it is not a big problem.
